/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface SvgInterface extends utils.Interface {
  contractName: "Svg";
  functions: {
    "byte2uint8(bytes,uint256)": FunctionFragment;
    "stringifyIntSet(bytes,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "byte2uint8",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stringifyIntSet",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "byte2uint8", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stringifyIntSet",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Svg extends BaseContract {
  contractName: "Svg";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SvgInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    byte2uint8(
      _data: BytesLike,
      _offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    stringifyIntSet(
      _data: BytesLike,
      _offset: BigNumberish,
      _len: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  byte2uint8(
    _data: BytesLike,
    _offset: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  stringifyIntSet(
    _data: BytesLike,
    _offset: BigNumberish,
    _len: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    byte2uint8(
      _data: BytesLike,
      _offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    stringifyIntSet(
      _data: BytesLike,
      _offset: BigNumberish,
      _len: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    byte2uint8(
      _data: BytesLike,
      _offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stringifyIntSet(
      _data: BytesLike,
      _offset: BigNumberish,
      _len: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    byte2uint8(
      _data: BytesLike,
      _offset: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stringifyIntSet(
      _data: BytesLike,
      _offset: BigNumberish,
      _len: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
