/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERC721KImage, IERC721KImageInterface } from "../IERC721KImage";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "input",
        type: "bytes",
      },
    ],
    name: "render",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC721KImage__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721KImageInterface {
    return new utils.Interface(_abi) as IERC721KImageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721KImage {
    return new Contract(address, _abi, signerOrProvider) as IERC721KImage;
  }
}
