/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC721KTraits,
  IERC721KTraitsInterface,
} from "../IERC721KTraits";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "input",
        type: "bytes",
      },
    ],
    name: "fetch",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC721KTraits__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721KTraitsInterface {
    return new utils.Interface(_abi) as IERC721KTraitsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721KTraits {
    return new Contract(address, _abi, signerOrProvider) as IERC721KTraits;
  }
}
