/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISVGModule, ISVGModuleInterface } from "../ISVGModule";

const _abi = [
  {
    inputs: [],
    name: "getEncoding",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "input",
        type: "bytes",
      },
    ],
    name: "render",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISVGModule__factory {
  static readonly abi = _abi;
  static createInterface(): ISVGModuleInterface {
    return new utils.Interface(_abi) as ISVGModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISVGModule {
    return new Contract(address, _abi, signerOrProvider) as ISVGModule;
  }
}
